### PR TITLE
Fix method of getting formula

### LINKED ISSUE #161: A formula cell return an empty formula
when a cell copy the  formula of above cell, the cell return empty formula.
we see  the code at line 144 of org.dhatim.fastexcel.reader.RowSpliterator shown as following:
image
the  t attribute of f node used "array". But I think it should be both "array" and "shared", because I uncompressed a sample xlsx  file 
 [Book2.xlsx](https://github.com/dhatim/fastexcel/files/6403114/Book2.xlsx)and checked line 43,"t" is "shared".
image

 Furthermore, a shared f node return formula is empty not null, so I add other logic at line 152.
image

### PR DESCRIPTION
**Pull request by meiMingle**
Fix #161 .The implementation of poi is a bit complicated for me, so the method of parsing sharedFormula here is adapted from [here](https://github.com/qax-os/excelize/blob/master/cell.go)

### CODE REVIEW

File: fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/BaseFormulaCell.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
+package org.dhatim.fastexcel.reader;
+
+public class BaseFormulaCell {
+    private CellAddress baseCelAddr;
+
+    private String formula;
+    private CellRangeAddress ref;
```
Comment (ochedru) [inline fastexcel-reader/src/main/java/org/dhatim/fastexcel/reader/BaseFormulaCell.java:7]: These attributes could be final

**Comment by ochedru** [comment]
Thank you for your PR!
